### ISSUE TITLE
Sort by other things than name

### ISSUE THREAD

**Issue by mgunyho** [mgunyho/tere#27]
Currently the listing is always sorted by name. Would be nice to also sort by e.g. date, although I have not had much use for this. In that case, should also add a date column to the listing. Should be configurable whether the sorting stays the same when entering a folder.

**Comment by joshrdane** [comment]
Mind if I work on this feature?

**Comment by mgunyho** [comment]
Hi!

Sure, go ahead! I haven't implemented this mostly because it requires figuring out quite a few details which I've been too busy/lazy to decide on:

- What properties do we want to sort by? I see that the directory listing of `vim` can sort by name, extension, size, and time (which I assume means modified time). The file [Metadata](https://doc.rust-lang.org/std/fs/struct.Metadata.html) provided by Rust also has info on last access and creation time (though the latter doesn't work on Ubuntu by default).
    - `tere` is mostly for browsing folders, so maybe size and extension are not so important? What do we report as the size of folders?
    - Do we want to have an option to "not sort directories first"? What about symlinks?
- If we for example support sorting by modification time, should we add a column that shows it? I think it would be good to see what we're sorting by, but this makes the main screen quite a bit more complicated:
    - Do we add column headers? Maybe not necessary, a line like `my_folder        2022-09-16 12:34` is quite easy to understand.
    - We need to figure out how to draw the columns if the screen is too narrow. This is especially tricky if we have more than two columns. One option would be to switch to a full-fledged UI framework like [tui-rs](https://github.com/fdehau/tui-rs) instead of reinventing the weel, but that would be a major undertaking.
- Things to do related to the UI:
   - Add CLI options to set the initial/default sort order
   - Add keyboard shortcuts for changing the sort order, maybe something like `Alt-S`.
   - Some way to specify if the sort order should be globally set or per-folder? I like this feature in e.g. [Dolphin](https://apps.kde.org/fi/dolphin/) that I can have my Downloads folder sorted by date, but Documents sorted alphabetically. Doing per-folder is more work, but we could store that info in the history file.

But please go ahead and make a PR and let's see where this goes.


Note: if you start working on this, see #62 (should be merged soon) which adds some functionality for handling changes to settings that affect the directory listing. I'm also working on some bug fixes related to the drawing of the main screen (I'll do a PR about these soon), which might conflict with this, but we can figure it out.

**Comment by joshrdane** [comment]
Hey, so I had the some of the same questions about the details.

- What properties do we want to sort by?
    - As far as date sorting, my intuition says to sort by last modified date although an argument along the lines of --sort <name | adate | cdate | mdate> could be used where adate=lastAccessedDate, cdate=creationDate, and mdate=modifiedDate.
    - Like you said, tere is mostly for browsing folders so I'd think the default would be sorting by folders first. Once again, we could add this kind of functionality with CLI arguments like `--files-first` `--folders-first` `--mixed`. In my opinion, symlinks should _ideally_ be treated like whichever type they point to.
- If we for example support sorting by modification time, should we add a column that shows it?
    - I also think it would be a good thing to see what we are sorting by, although if we're not using a UI framework at this point, I'd say to only add an additional column that corresponds with displaying the column header the user is sorting by and the values associated with that column. For example, if they're sorting by name as default, they either get the current UI setup with no headers but if they decide to sort by modified date they get a `name` column and a `modified date` (or abbreviated form) column.
    - I think using something like tui-rs may be useful at some point in the project, but may be beyond the scope of this particular issue.
    - My inclination for what to do if the screen is too narrow is to drop the date column. I think trying to display too much information on screen will make it feel clunky
- UI
    - As far as sorting order per folder, I would think we can set the folder options to have precedence to the global sorting order. The implementation of this may be tricky though.
        - What happens if they change the sorting order while inside a folder? Does it stay the same next time you visit the folder? If so, that seems like there wouldn't much use for the CLI arguments. Maybe we store per-folder sort order but if they specify the sort order CLI arguments, the per-folder sort settings get ignored unless they use the keyboard shortcut to change the sort order which would change the per-folder setting?
