### ISSUE TITLE
Provide musl binary

### ISSUE THREAD

**Issue by Timmmm** [mgunyho/tere#32]
I have to use an ancient weird Centos system that has an ancient glibc. It would be nice if you could provide a musl version of this.

I have set up a CLI Rust project before to use the free Github Actions runners to do this and automatically attach the binaries to a Github release. This will let you build it for Mac and Linux too.

Feel free to copy [my code](https://github.com/Timmmm/autorebase/tree/master/.github/workflows) - the `build.yml` does not build with Musl to keep things simple. The `release.yml` does though.

The release attaching thing is a little weird to be honest. Alternatively you can just upload the build artefacts to the CI run and then manually make a release from them.

See [here](https://github.com/Timmmm/robocut/blob/develop/.github/workflows/build.yaml#L45) for an example of that.

**Comment by mgunyho** [comment]
Thanks for the examples! I will need to look into CI at some point, but for now I'm just going to hack with the `build-release.sh` script and upload manually.

I added a musl binary to the v1.1.0 release, let me know if it works for you!

**Comment by Timmmm** [comment]
That was fast, thanks! Works perfectly!

I'll close this so you don't have it weighing on your mind. I definitely recommend Github Actions though. So much easier cross-platform testing/building, and it has a solid UI.

The only thing I really hate about it is the only way to test config changes is to commit them and wait to see if they work. Very tedious.
