### ISSUE TITLE
libc error in ubuntu bionic

### ISSUE THREAD

**Issue by moxgreen** [mgunyho/tere#43]
Trying tere on ubuntu bionic I obtained
```
./tere: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by ./tere)
./tere: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./tere)
```
and
```
ls -l /lib/x86_64-linux-gnu/libc.so.6
lrwxrwxrwx 1 root root 12 mag  3 12:19 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.27.so*
```

**Comment by mgunyho** [comment]
Hi! Yes, `tere` is built on ubuntu 20.04 for now, so the glibc version will be newer. Can you try the musl binary if it works for you?

**Comment by mgunyho** [comment]
I'll close this for now, let me know if the musl version of the latest release (v1.2.0) doesn't work for you.
