### ISSUE TITLE
Exiting tere with CTRL+C produces prints with mouse cursor position

### ISSUE THREAD

**Issue by pajakpawel** [mgunyho/tere#45]
Hi!
I have recently downloaded and configured tere on my Linux and I encountered some bug.
When I exit tere with CTRL + C (as suggested in README to exit tere without changing directory)
the mouse cursor position is printed in terminal with every move of my mouse.

To reproduce this:
- run tere with command `tere --mouse=on` 
- exit tere with `CTRL + C`
- move your mouse around

Result:
![obraz](https://user-images.githubusercontent.com/32963953/179951534-535a5dce-357c-4808-8eb0-e78193553248.png)

My config in `.bashrc`:
![obraz](https://user-images.githubusercontent.com/32963953/179951817-08c6a547-02ac-4717-a3f3-2f48a7d1d1f7.png)

My OS  base info:
![obraz](https://user-images.githubusercontent.com/32963953/179961399-7e766537-3cd4-4174-892a-41e50fd85b88.png)

**Comment by mgunyho** [comment]
Thanks! I can reproduce this. It should not be hard to fix, but it might take a while before I have time to do it.

**Comment by mgunyho** [comment]
This is fixed in 874901039d0b2a0396b8b480cf2153c75d4b0346, it will be available in the next release soon!

**Comment by pajakpawel** [comment]
I've just downloaded tere v1.2.0 and it works perfectly, thanks a lot!
