### ISSUE TITLE
Add a subcommand to print shell wrappers

### ISSUE THREAD

**Issue by superatomic** [mgunyho/tere#47]
As discussed previously in #29, it seems very useful for the `tere` binary itself to provide access to [the shell wrappers for `tere` that are listed in the README](https://github.com/mgunyho/tere/tree/a8d71bf7defc2daee824e44d9b314b524c9a2889#setup). This can then be used to provide simple one line commands that can be added to shell startup scripts, which has the added benefits of being simpler, easier to change in the future, and more seamless (the correct path to the `tere` binary could be automatically filled in).

For example, to setup the `tere` shell wrapper for bash and zsh, the following would just need to be added to a startup file (like `~/.bash_profile`):

```bash
eval "$(tere init bash)"
```

This would greatly improve the experience of installing `tere`.

If this idea is approved, I would be happy to implement this feature and submit a PR with it implemented.

**Comment by superatomic** [comment]
Oops, this is around the same idea as #46. I guess this shows that this idea is wanted.

**Comment by mgunyho** [comment]
Thanks for the suggestion and explanation! Let's indeed discuss this in #46.
