### ISSUE TITLE
Custom keyboard shortcuts

### ISSUE THREAD

**Issue by mgunyho** [mgunyho/tere#48]
As I anticipated, this is a fairly popular request.

I will need to hash out the syntax. I want it to be obvious (something like `--map ctrl+x:ACTIONNAME` to bind <kbd>ctrl</kbd><kbd>X</kbd> to something. Something more explicit/easier to understand than the emacs-style `C-x`.). Perhaps there already exists one or more crates to parse such options. Suggestions/opinions welcome.

Related: #35  #39

**Comment by gervaisb** [comment]
At least, it should be great to remap `Esc` and `Alt+q`. Or add one. 
I would like to hit `Cmd+Enter` to exit-and-go-to-selected-folder.

**Comment by mgunyho** [comment]
This is now implemented (see #57), it will be available in the next release soon.
