### ISSUE TITLE
feature `strip` is required

### ISSUE THREAD

**Issue by evgn88** [mgunyho/tere#50]
[root@rpi tere-rs]# cargo install tere
    Updating crates.io index
error: failed to download `tere v1.1.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tere-1.1.0/Cargo.toml`

Caused by:
  feature `strip` is required

  The package requires the Cargo feature called `strip`, but that feature is not stabilized in this version of Cargo (1.58.0).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-strip-option for more information about the status of this feature.

how install strip?

**Comment by mgunyho** [comment]
You need to update rust/cargo to version 1.59 or later, as mentioned in the link https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-strip-option

**Comment by mgunyho** [comment]
I'll close this for now, let me know if it still doesn't work after you have updated rustc/cargo to >= 1.59.
