### ISSUE TITLE
Feature requset - will be awesome add one more hotkey

### ISSUE THREAD

**Issue by TAI-REx** [mgunyho/tere#52]
Hello everyone!
It will be great if tool such this will have a hotkey which will spawn terminal in location was browsed via it.
If I will got some free time - will PR that func soon.
Thx a lot.

**Comment by mgunyho** [comment]
Hi, thanks for the suggestion. However, I don't quite understand why you would want to do that. If you have set up tere correctly, the outer terminal will end up where you navigated to when you exit. You could think of exiting as "spawning a terminal at the location".

**Comment by mgunyho** [comment]
I'll close this for now, but feel free to reopen it if you think this is important and can clarify your idea.
