### ISSUE TITLE
feature request: add a shortcut to toggle filter-search/no-filter-search

### ISSUE THREAD

**Issue by metasong** [mgunyho/tere#59]
convenient to filter out unrelavent files/folders in the gap-anywhere search mode, if some highlights are far more pages away

**Comment by mgunyho** [comment]
I started working on this in #62, but it's a bit trickier than expected, see the comment in there. This will probably not be in the next release but I'll work on it after that.

**Comment by mgunyho** [comment]
This is now implemented. I will make a new release including this in the near future.
