### ISSUE TITLE
How to enable the normal search but not from start?

### ISSUE THREAD

**Issue by metasong** [mgunyho/tere#63]
I tried -no-gap-search switch, but it searches from start

**Comment by mgunyho** [comment]
Good question! The answer is [here](https://github.com/mgunyho/tere/blob/master/src/cli_args.rs#L131). Basically, it's not implemented because I didn't know if anybody would want to do that. But maybe I'll now do it.

**Comment by mgunyho** [comment]
This is fixed by https://github.com/mgunyho/tere/commit/bfb5287b7cae3a810926d872d81b2b6083cacc16, it will be available in the next release soon.
