### ISSUE TITLE
Not an alternative to change dir, but ls, yes

### ISSUE THREAD

**Issue by AddictArts** [mgunyho/tere#66]
Thanks for this cool tool, but it advertises cd, but there is no clear way to cd. I have tried alt-enter and ctrl-space and these do not change the current directory.  Seems like such a simple thing, but the CD part is buried and not discussed or shown in the README or gif at least that I can find.

Oddly the directory is echo'd to the terminal, but the current dir is unchanged.  I am guessing the idea is to `cd $(tere)` or something like that which is undesirable. That works, but the extra needed typing limits usage. I'll just type `cd .config`. I must be missing something here.

**Comment by BornIncompetence** [comment]
The README literally shows you how to setup `cd` for your specific shell in the second step of Setup.

> 2. Configure your shell to `cd` to the folder which `tere` prints when it exits. It has to be usually done using a function or alias, since a subprocess cannot change the working directory of the parent. See instructions for your shell below.

**Comment by AddictArts** [comment]
> The README literally shows you how to setup `cd` for your specific shell in the second step of Setup.
> 
> > 2. Configure your shell to `cd` to the folder which `tere` prints when it exits. It has to be usually done using a function or alias, since a subprocess cannot change the working directory of the parent. See instructions for your shell below.

Ah, indeed. Oops. I think the issue is it is really easy to see the `cd` function listed up front, then the gif demo doesn't convey it's usage really. It might be useful to state before install, shell configuration is needed. Just my observation. Thanks

**Comment by mgunyho** [comment]
No worries! You're not the first one who has had this problem, which tells me that maybe the README could be clarified. Do you have any specific suggestion what it should say?

**Comment by AddictArts** [comment]
@mgunyho Thanks for asking. I'd switch the Setup number 1 and 2. So, 2 becomes 1. You may want to say something like prior to install for tere really to work, your shell needs to be configured otherwise half the function of tere is lost. Apologies if half is too aggressive, but it does seem like it is the point of tere, being able to cd.

**Comment by mgunyho** [comment]
I have now updated the README to mention the shell config before the setup instructions as well. Hopefully this clarifies it more. I didn't swap the order of the setup instructions, because it feels confusing to talk about setting up a shell alias for running a program that you don't yet have.
