### ISSUE TITLE
Consider joining Hacktoberfest 

### ISSUE THREAD

**Issue by frazar** [mgunyho/tere#70]
Hacktoberfest is an interesting and low-hassle way to attract contributors. More info [here](https://hacktoberfest.digitalocean.com/).

To do so, it should be sufficient to add the hacktoberfest label to the GitHub repository.

**Comment by mgunyho** [comment]
Thanks for the suggestion! Unfortunately, I don't think I have enough time right now to handle a lot of extra PRs, and there are not that many issues to fix.
