### ISSUE TITLE
Add continuous integration workflow

### ISSUE THREAD

**Issue by orhun** [mgunyho/tere#73]
It would be nice to test/fmt/clippy `tere` via [GitHub Actions](https://github.com/features/actions) on each push. I would like to provide a PR if applicable.

**Comment by mgunyho** [comment]
Thanks for the suggestion! I think for now CI is not necessary, `tere` is such a small project that I think it would add more overhead than what it's worth. It also opens a slippery slope to depend on Github's proprietary features more and more, which I don't really like.
