### ISSUE TITLE
Change to current directory and exit

### ISSUE THREAD

**Issue by orhun** [mgunyho/tere#76]
I'm trying out `tere` and I have this simple use-case. For example:

I want to enter the directory `c` while viewing the contents of it:

![capture](https://user-images.githubusercontent.com/24392180/195164278-8e8a5b80-7e70-4c95-9e04-0f99096d1aae.png)

I need to go back (press left arrow key) and press Alt-Enter to `cd` into it and exit. Is it possible to `cd` to the currently viewed directory via `tere`? (Or is there a shell trick that I can use?)

**Comment by mgunyho** [comment]
Yes, if you have configured the shell correctly, exiting `tere` will `cd` to the current folder.

**Comment by orhun** [comment]
Ah, great! Didn't realize that. Thanks!
