### ISSUE TITLE
Feature request: Config option to disable/enable autoselect

### ISSUE THREAD

**Issue by BigCrow** [mgunyho/tere#95]
Is it possible to have a configuration option to disable the autoselect when searching & there is only 1 option left.
You could often enter into multiple folders by accident when typing fast.

For example you could be typing the full name of a folder & enter it before you finish typing, making you enter into another folder afterwards as well.

**Comment by mgunyho** [comment]
This can be done with `--autocd-timeout=no`. The default value of 200 ms was chosen so that the situation you mention would not happen that often (for me it works well), but I understand if you want to turn it off.
